Customizable footer layout
Siphalor/dhbw-pandoc-paper-template pull request #3
Opened 2022-08-09 08:52 UTC by ProphetLamb

The specification document of the DHBW Mosbach, defines that the pagemark should be located on the right side of the page, and the author names on the left side.
This pr implements this, while allowing to reset to the previous layout, by commenting
```yaml
  pagemark:
    left: true
  authors: true 
```
in [index.md](./index.md).

2022-08-09 08:53 UTC, ProphetLamb commented
Warum habe ich das auf Englisch geschrieben? - Gute Frage, nächste Frage

2022-08-10 12:56 UTC, Siphalor requested changes

2022-08-10 12:56 UTC, Siphalor commented on index.md
> +  authors: true # Include authors in footer, away from the pagemark.
I don't think roman pagemarks should be enabled by default.
Also, it should probably be put into the general `footer.pagemark` section.

```suggestion
# index-roman: true # Use roman numerals for indices in content tables

footer:
  pagemark:  # Determine where the page counter is located, default is center, options are right & left
    left: true
    roman: false
  authors: true # Include authors in footer, away from the pagemark.
```

2022-08-10 12:56 UTC, Siphalor commented on index.md
> +```
SVG support isn't really in scope for this pr.
I'm also not really a fan of installing scoop manifests directly, as there won't be support for auto-updates, afaik.

Some buckets with `librsvg` can be found [here](https://scoop.sh/#/apps?q=rsvg&s=2&d=1&o=false).

Also, there are a bunch of grammar/spelling mistakes:

````suggestion
[SVG](https://developer.mozilla.org/en-US/docs/Web/SVG) können mit GNOME `librsvg` eingebettet werden. In Windows muss diese Library manuell nachbezogen werden.
```pwsh
scoop install https://gist.githubusercontent.com/LuminousPath/55c9a416ab8530cd5875e29e8197f22c/raw/fa5ef794486acfa3d130028b9626d24c7d1ed5ad/rsvg-convert.json
```
````

2022-08-10 12:56 UTC, Siphalor commented on pandoc/template.latex
> +$endif$ %(footer.authors)
No support for centered pagemarks?

2022-08-10 12:59 UTC, Siphalor commented
First off, I must be blind, because in the official recommendations for the papers, there seems to be no evidence for either footer requirements or Roman numerals.

The official example PDF for bachelor papers uses centered Arabic numerals in the footer.

The part for SVGs doesn't really fit this PR.

2022-08-10 17:30 UTC, closed without merging